import {
  Activity as ActivityGlyph,
  AlarmClockCheck,
  Bandage,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Calculator,
  CalendarCheck,
  Camera,
  Car,
  ChefHat,
  Cigarette,
  Clipboard,
  Coffee,
  CreditCard,
  Dumbbell,
  Footprints,
  Gamepad2,
  GlassWater,
  GraduationCap,
  Guitar,
  HandCoins,
  Headphones,
  Landmark,
  Leaf,
  ListChecks,
  Mail,
  Moon,
  Music,
  Newspaper,
  NotebookPen,
  Palette,
  PawPrint,
  PenLine,
  Phone,
  PiggyBank,
  Pill,
  PillBottle,
  Plane,
  Puzzle,
  Receipt,
  Repeat,
  Salad,
  Scissors,
  ShoppingCart,
  ShowerHead,
  Smartphone,
  Smile,
  Snowflake,
  Sparkles,
  SprayCan,
  Stethoscope,
  Sun,
  Sunrise,
  Sunset,
  Syringe,
  Thermometer,
  Timer,
  Trash2,
  Umbrella,
  Utensils,
  Video,
  Wallet,
  WashingMachine,
  Wifi,
  Wind,
  Zap,
  type LucideIcon,
} from "lucide-react"

// Order matters: first regex match wins, so more specific keywords (e.g. a
// named pet) are listed before broader ones they'd otherwise be swallowed by
// (e.g. a generic walk/outdoors match).
export const KEYWORD_ICONS: [RegExp, LucideIcon][] = [
  // meds & medical
  [/vitamin|supplement/i, PillBottle],
  [/med(s|ication|icine)?\b/i, Pill],
  [/inject|insulin|syringe/i, Syringe],
  [/dentist|dental|floss|brush(ing)? teeth/i, Smile],
  [/doctor|checkup|appointment|physio/i, Stethoscope],
  [/therapy|therapist|counsel(l)?ing/i, Brain],
  [/wound|bandage|first aid/i, Bandage],
  [/fever|temperature|thermometer/i, Thermometer],
  [/shower|bath\b|hygiene/i, ShowerHead],
  [/skincare|moisturi[sz]e/i, Sparkles],
  [/haircut|shave/i, Scissors],
  [/smoking|cigarette|vape/i, Cigarette],

  // fitness & movement
  [/gym|workout|exercise|lift(ing)?|cardio/i, Dumbbell],
  [/yoga|stretch|mobility/i, ActivityGlyph],
  [/meditat|breath(e|ing)|mindful/i, Wind],
  [/cycle|cycling|bike/i, Bike],
  [/swim/i, ActivityGlyph],
  [/\brun(ning)?\b|jog/i, Footprints],
  [/dog|cat|pet\b/i, PawPrint],
  [/plant|garden/i, Leaf],
  [/walk|hike|outside|park\b/i, Footprints],

  // food & drink
  [/water|hydrate/i, GlassWater],
  [/coffee|tea\b/i, Coffee],
  [/salad|healthy eat|diet/i, Salad],
  [/grocer(y|ies)|shopping/i, ShoppingCart],
  [/cook|dinner|lunch|breakfast|meal|recipe/i, ChefHat],
  [/dishes|kitchen/i, Utensils],

  // chores & home
  [/laundry|washing/i, WashingMachine],
  [/trash|garbage|bins?/i, Trash2],
  [/disinfect|sanitize|spray/i, SprayCan],
  [/clean|tidy|dust|vacuum|declutter/i, Sparkles],
  [/shirt|dress|iron(ing)?/i, Sparkles],

  // work & study
  [/deep work|work|code|coding|focus session/i, Briefcase],
  [/study|homework|class|course/i, GraduationCap],
  [/read(ing)?|book\b/i, BookOpen],
  [/journal|write|writing|blog/i, NotebookPen],
  [/plan|todo|review/i, ListChecks],
  [/pomodoro|timer/i, Timer],
  [/note\b/i, PenLine],
  [/clipboard|checklist/i, Clipboard],

  // finance
  [/budget|tax(es)?/i, Calculator],
  [/bill|invoice/i, Receipt],
  [/save|savings/i, PiggyBank],
  [/debt|credit card|pay off/i, CreditCard],
  [/bank/i, Landmark],
  [/donate|tip\b/i, HandCoins],
  [/finance|money|wallet/i, Wallet],

  // social & comms
  [/stand-?up|meeting|zoom/i, Video],
  [/phone call|call\b/i, Phone],
  [/email|inbox/i, Mail],
  [/text|message/i, Smartphone],

  // hobbies & creative
  [/guitar|piano|instrument|practice/i, Guitar],
  [/music|playlist/i, Music],
  [/podcast|listen/i, Headphones],
  [/paint|draw|art\b/i, Palette],
  [/photo|camera/i, Camera],
  [/game|gaming/i, Gamepad2],
  [/puzzle|brain game/i, Puzzle],
  [/news|newspaper/i, Newspaper],

  // errands & travel
  [/drive|commute|car\b/i, Car],
  [/flight|travel|trip/i, Plane],

  // sleep & rhythm
  [/wake|morning routine/i, Sunrise],
  [/wind down|sleep|bed|screens/i, Moon],
  [/evening routine/i, Sunset],
  [/sun\b/i, Sun],
  [/rain|umbrella/i, Umbrella],
  [/cold|snow/i, Snowflake],

  // misc / self-care
  [/streak|habit|repeat/i, Repeat],
  [/energy|recharge/i, Zap],
  [/offline|digital detox|wifi/i, Wifi],
  [/alarm|reminder/i, AlarmClockCheck],
  [/calendar|schedule/i, CalendarCheck],
]
